sudo: false

language: node_js

node_js:
  - "6"
  - "8"
  - "10"

install:
  - yarn

script:
  - yarn test

cache:
  - yarn
  - directories:
    - "node_modules"

jobs:
  include:
    - stage: coverage
      node_js: "8"
      - script: yarn add -D coveralls
      - script: jest --verbose --coverage --collectCoverageFrom=src/**/* && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
