sudo: false

language: node_js

node_js:
  - "6"
  - "8"
  - "10"

install:
  - yarn

script:
  - yarn build
  - yarn test

cache:
  - yarn
  - directories:
    - "node_modules"

jobs:
  include:
    - stage: coverage
      node_js: "8"
      script: 
        - jest --verbose --coverage --collectCoverageFrom=src/**/*
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
        - rm -rf ./coverage
    - stage: npm release
      node_js: "8"
      script: 
        - yarn build
        - echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        email: $NPM_EMAIL
        skip_cleanup: true
        on:
          tags: true
